const actions = {
  SALVAR_EMAIL: 'SALVAR_EMAIL',
  SALVAR_ENDERECO: 'SALVAR_ENDERECO',
  SALVAR_TELEFONE: 'SALVAR_TELEFONE',
  SALVAR_DATA_NASC: 'SALVAR_DATA_NASC',
  SALVAR_CPF: 'SALVAR_CPF',
  SALVAR_NOME: 'SALVAR_NOME',
  SALVAR_STATUS: 'SALVAR_STATUS',
  SALVAR_DATA_PREVISTA: 'SALVAR_DATA_PREVISTA'
}

export default actions
