const actions = {
  SALVAR_ALUNOS: 'SALVAR_ALUNOS',
  SALVAR_CLINICA: 'SALVAR_CLINICA',
  SALVAR_DATA: 'SALVAR_DATA',
  SALVAR_HORARIO: 'SALVAR_HORARIO',
  SALVAR_PACIENTE: 'SALVAR_PACIENTE',
  SALVAR_PACIENTE_ID: 'SALVAR_PACIENTE_ID',
  SALVAR_ALUNO_ID: 'SALVAR_ALUNO_ID',
}

export default actions
