const actions = {
  SALVAR_PERIODO: 'SALVAR_PERIODO',
  SALVAR_TURNO: 'SALVAR_TURNO',
  SALVAR_PROCEDIMENTO: 'SALVAR_PROCEDIMENTO',
  SALVAR_ID_PROCEDIMENTO: 'SALVAR_ID_PROCEDIMENTO'
}

export default actions
